server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bd_api_navarro?zeroDateTimeBehavior=convertToNull&serverTimeZone=UTC
    username: root
    password: root
    initialization-mode: always
logging:
  level:
    '[com.init.api]': DEBUG
